name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Use the recommended permissions for GitHub Pages
permissions:
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Documents
        uses: actions/checkout@v4
        with:
          repository: robstarbuck/documents
          path: src/documents
          ref: main # <-- Explicitly checks out the 'main' branch

      - name: Checkout Content
        uses: actions/checkout@v4
        with:
          repository: robstarbuck/content.robstarbuck.uk
          path: src/posts
          ref: main # <-- Also made this explicit for consistency

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno task build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This should be the output directory from your build script
          path: '_site'

  # Deployment job
  deploy:
    # Requires the build job to be successful
    needs: build
    runs-on: ubuntu-latest
    
    # Specifies the deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4