name: Build and Deploy to gh-pages branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# This permission allows the action to push a commit to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Documents
        uses: actions/checkout@v4
        with:
          repository: robstarbuck/documents
          path: src/documents
          ref: main # Explicitly checking out the 'main' branch

      - name: Checkout Content
        uses: actions/checkout@v4
        with:
          repository: robstarbuck/content.robstarbuck.uk
          path: src/posts
          ref: main # Explicitly checking out the 'main' branch

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno task build

      - name: Deploy to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # The branch you want to deploy to
          target_branch: gh-pages
          # The directory the action should deploy
          build_dir: _site
        env:
          # The GITHUB_TOKEN is automatically created by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}