
name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Documents
        uses: actions/checkout@v4
        with:
          repository: robstarbuck/documents
          path: src/documents

      - name: Checkout Content
        uses: actions/checkout@v4
        with:
          repository: robstarbuck/content.robstarbuck.uk
          path: src/posts
          
      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno task build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          target_branch: gh-pages
          build_dir: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
